const PDFDocument = require('pdfkit');
const QRCode = require('qrcode');

class PDFService {

  /**
   * Generate a PDF with QR codes for a batch of serial numbers
   * Returns a Buffer containing the PDF
   */
  async generateQRCodeSheet(serials, productInfo) {
    return new Promise(async (resolve, reject) => {
      try {
        const doc = new PDFDocument({
          size: 'A4',
          margin: 30,
          info: {
            Title: `MediTrack QR Codes - ${productInfo.productName} - ${productInfo.batchNumber}`,
            Author: 'MediTrack System',
            Subject: 'Medicine QR Code Labels'
          }
        });

        const buffers = [];
        doc.on('data', (chunk) => buffers.push(chunk));
        doc.on('end', () => resolve(Buffer.concat(buffers)));

        // Title
        doc.fontSize(16).font('Helvetica-Bold')
          .text('MediTrack — QR Code Sheet', { align: 'center' });
        doc.moveDown(0.3);
        doc.fontSize(10).font('Helvetica')
          .text(`Product: ${productInfo.productName} (${productInfo.strength})`, { align: 'center' });
        doc.text(`Batch: ${productInfo.batchNumber} | Expiry: ${productInfo.expiryDate}`, { align: 'center' });
        doc.text(`Generated: ${new Date().toLocaleString()} | Total: ${serials.length} codes`, { align: 'center' });
        doc.moveDown(0.5);

        // Draw a line
        doc.moveTo(30, doc.y).lineTo(565, doc.y).stroke('#cccccc');
        doc.moveDown(0.5);

        // QR codes — 3 per row, with serial text below
        const qrSize = 120;
        const colWidth = 175;
        const startX = 30;
        let x = startX;
        let y = doc.y;
        let col = 0;

        for (let i = 0; i < serials.length; i++) {
          const serial = serials[i];

          // Check if we need a new page
          if (y + qrSize + 40 > 780) {
            doc.addPage();
            y = 30;
            x = startX;
            col = 0;
          }

          // Generate QR code as PNG buffer
          const gs1Data = serial.gs1_data || serial.serial_number;
          const qrBuffer = await QRCode.toBuffer(gs1Data, {
            type: 'png',
            width: qrSize,
            errorCorrectionLevel: 'H',
            margin: 1
          });

          // Draw border
          doc.save();
          doc.rect(x, y, colWidth - 10, qrSize + 35).stroke('#e0e0e0');
          doc.restore();

          // Draw QR image
          doc.image(qrBuffer, x + (colWidth - 10 - qrSize) / 2, y + 5, { width: qrSize, height: qrSize });

          // Serial number text under QR
          doc.fontSize(6).font('Helvetica')
            .text(serial.serial_number, x + 5, y + qrSize + 8, { width: colWidth - 20, align: 'center' });

          col++;
          if (col >= 3) {
            col = 0;
            x = startX;
            y += qrSize + 45;
          } else {
            x += colWidth;
          }
        }

        // Footer on last page
        doc.moveDown(2);
        doc.fontSize(8).font('Helvetica')
          .text('Generated by MediTrack Anti-Counterfeit System', { align: 'center', color: '#999999' });

        doc.end();
      } catch (error) {
        reject(error);
      }
    });
  }
}

module.exports = new PDFService();
